# Generated by Django 3.0.6 on 2020-09-19 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do autor')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento do autor')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Filosofia', 'Filosofia'), ('Religiao', 'Religiao'), ('Ciencia', 'Ciencia'), ('Romance', 'Romance'), ('Historia', 'Historia')], max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200, verbose_name='Rua')),
                ('bairro', models.CharField(max_length=200, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=200, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=200, verbose_name='Estado')),
                ('numero', models.IntegerField(default=0, verbose_name='Numero')),
            ],
            options={
                'verbose_name': 'Endereco',
                'verbose_name_plural': 'Enderecos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preco')),
                ('estoque', models.IntegerField(default=0, verbose_name='Estoque')),
                ('preco_total', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Preco Total')),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='livraria.Endereco')),
            ],
            options={
                'verbose_name': 'Editora',
                'verbose_name_plural': 'Editoras',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='livraria.Produto')),
                ('edicao', models.IntegerField(default=1, verbose_name='Edicao')),
                ('ano', models.DateField(verbose_name='Ano')),
                ('num_paginas', models.IntegerField(default=0, verbose_name='Numero de paginas')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descricao')),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='livraria.Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='livraria.Categoria')),
                ('editora', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editora', to='livraria.Editora')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
            bases=('livraria.produto',),
        ),
        migrations.CreateModel(
            name='EmprestimoLivro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateTimeField(auto_now_add=True, verbose_name='Data inicial')),
                ('data_devolucao', models.DateField(verbose_name='Data de devolução')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preco')),
                ('ativo', models.BooleanField(default=False)),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livro', to='livraria.Livro')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
            },
        ),
    ]
