# Generated by Django 3.0.6 on 2020-09-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0003_auto_20200920_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimolivro',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preco total'),
        ),
    ]
