# Generated by Django 3.0.5 on 2020-04-19 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinion', to='blog.Post'),
        ),
    ]
